name: 'Ansible playbook runner via SSH Action'
description: 'Runs ansible playbooks located on a remote server'
author: 'GitHub'
inputs: 
  playbook:
    description: Playbook to run
    default: provision-infra-web.yml
  control_host:
    description: Control host to SSH onto and run playbooks on
    required: true
  control_user: 
    description: Username for control host
    required: true
  control_ssh_key: 
    description: SSH key for control host
    required: true
  directory:
    description: Git directory on control host where playbooks are located
    required: true
  vault_pass:
    description: Password to unlock vault
    required: true
  tags:
    description: Tags to pass to ansible-playbook command
    required: true
  port:
    description: Port used to ssh into control host
    required: true
  
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.control_ssh_key }}
    - ${{ inputs.control_user }}
    - ${{ inputs.control_host }}
    - ${{ inputs.directory }}
    - ${{ inputs.vault_pass }}
    - ${{ inputs.playbook }}
    - ${{ inputs.tags }}
    - ${{ inputs.port }}
